name: Update PR Title for Merge Label

on:
  pull_request_target:
    types: [labeled]

jobs:
  update-title:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update PR Title
        if: github.event.label.name == 'merge'
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          BASE_BRANCH=${{ github.event.pull_request.base.ref }}
          PR_TITLE="${{ github.event.pull_request.title }}"

          if [[ "$BASE_BRANCH" == "develop" ]]; then
            NEW_TITLE="Merge to develop dev-v: $PR_TITLE"
          elif [[ "$BASE_BRANCH" == "main" ]]; then
            NEW_TITLE="Merge to main v: $PR_TITLE"
          else
            NEW_TITLE="$PR_TITLE"
          fi

          echo "New title: $NEW_TITLE"

          curl \
            -X PATCH \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{\"title\":\"$NEW_TITLE\"}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER"
