name: Update PR Title

on:
  pull_request_target:
    types: [labeled]

jobs:
  update-title:
    if: github.event.label.name == 'merge'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update PR Title
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          NEW_TITLE="Merge to v- ${{ github.event.pull_request.title }}"
          echo "New title: $NEW_TITLE"

          curl \
            -X PATCH \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{\"title\":\"$NEW_TITLE\"}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER"
